name: go unit tests

on: 
  pull_request:
    branches:
      - main
      - dev

jobs:
  libft:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.6'
    - run: go test ./... -cover -covermode atomic
