name: libft unit tests

on:
  issue_comment:                                     
    types: [created, edited, deleted]

  pull_request:
    branches:
      - main

jobs:
 libft:
   if: contains(github.event.comment.html_url, '/pull/')
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: Make pilates dir inside test data folder and copy unit tests
       if: contains(github.event.comment.body, '/libft')
       run: |
        mkdir ${{ github.workspace }}/testdata/libft/pilates
        cp -R ${{ github.workspace }}/libft/* ${{ github.workspace }}/testdata/libft/pilates/*
        ls ${{ github.workspace }}/testdata/libft/pilates
        rm ${{ github.workspace }}/testdata/libft/pilates/CMakeLists.txt
        cp ${{ github.workspace }}/libft/CMakeLists.txt.test ${{ github.workspace }}/testdata/libft/pilates/CMakeLists.txt
        cp ${{ github.workspace }}/libft/CMakeLists.txt.in ${{ github.workspace }}/testdata/libft/CMakeLists.txt.in
        cp ${{ github.workspace }}/libft/CMakeLists.txt ${{ github.workspace }}/testdata/libft/CMakeLists.txt
     - name: Cmake
       run: |
        cmake -S . -B build
        cmake --build build
       working-directory: ${{ github.workspace }}/testdata/libft
     - name: Run tests
       run: |
        ctest --output-on-failure
       working-directory: ${{ github.workspace }}/testdata/libft/build