name: libft unit tests

on:
  issue_comment:                                     
    types: [created, edited, deleted]

  pull_request:
    branches:
      - main

jobs:
 libft:
   if: contains(github.event.comment.html_url, '/pull/')
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: Make pilates dir inside test data folder and copy unit tests
       if: contains(github.event.comment.body, '/libft')
       run: |
        mkdir ./testdata/libft/pilates
        cp -r libft ./testdata/libft/pilates
        cp ./libft/CMakeLists.txt.test ./testdata/libft/CMakeLists.txt
     - name: Cmake
       run: |
        cmake -S . -B build
        cmake --build build
       working-directory: cd ./testdata/libft
     - name: Run tests
       run: |
        ctest --output-on-failure
       working-directory: ./testdata/libft/build