name: libft unit tests

on:
  issue_comment:                                     
    types: [created, edited, deleted]

  pull_request:
    branches:
      - main

jobs:
 libft:
   if: contains(github.event.comment.html_url, '/pull/')    # check if the comments come from pull request, exclude those from issue.
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: build and run unit tests on /libft command
       if: contains(github.event.comment.body, '/libft')   # check the comment if it contains the keywords
       run: |
        mkdir ${{ github.workspace }}/testdata/libft/pilates
        cp -r libft ${{ github.workspace }}/testdata/libft/pilates
        cp ${{ github.workspace }}/libft/CMakeLists.txt.test ${{ github.workspace }}/testdata/libft/CMakeLists.txt
        ls ${{ github.workspace }}/testdata/libft/
        cd ${{ github.workspace }}/testdata/libft/ && cmake -S . -B build
        cd ${{ github.workspace }}/testdata/libft/ && cmake --build build
        cd ${{ github.workspace }}/testdata/libft/build && ctest --output-on-failure
