name: libft unit tests

on:
  issue_comment:                                     
    types: [created, edited, deleted]

  pull_request:
    branches:
      - main

jobs:
 libft:
   if: contains(github.event.comment.html_url, '/pull/')    # check if the comments come from pull request, exclude those from issue.
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: build and run unit tests on /libft command
       if: contains(github.event.comment.body, '/libft')   # check the comment if it contains the keywords
       run: |
        cp -r libft ./testdata/libft/pilates \
        cp ./libft/CMakeLists.txt.test ./testdata/libft/CMakeLists.txt \
        cmake -S . -B build \
        cmake --build build \
        cd build && ctest --output-on-failure
