name: libft

on:
  pull_request:
    types: [closed]
    # branches:
    #   - main

jobs:
  release:
    # if: contains(github.event.pull_request.labels.*.name, 'Update')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.34.0
      env:
        GITHUB_TOKEN: ${{ secrets.GORELEASER }}
        WITH_V: true